### PR TITLE
fix: resolved problem with sending transaction by private key provider

### PR DESCRIPTION
**Pull request by polkom21**
Hello!
I have fixed the signature signing problem for private key provider. Tests are passing correctly so the other functionality should not be affected by this change. If you want I can still send you a usage example using private key provider.

### CODE REVIEW

**Comment by Yakuhito** [comment]
Hey there,

I've reviewed this commit, and there's indeed an issue in the `StandardCoin` class. However, your solution does not seem to work, since the solution included in the test cases before your modification is correct. You can check that with brun:

Initial:
```
(venv) yakuhito@catstation:~/projects/clvm_tools$ brun -x 01 ff80ffff01ffff33ffa0099fb6be4707dde8e4ca595d34fbe8fa99cb30ca756d99c63a4d3dac1fd899f0ff8502540be40080ffff33ffa054801b54fbae6bef63a77bd40222efe1fb1c78e8accf94f5271794be70d8b3b6ff840208d4cc80ffff34ff648080ff8080
(() (q (51 0x099fb6be4707dde8e4ca595d34fbe8fa99cb30ca756d99c63a4d3dac1fd899f0 0x02540be400) (51 0x54801b54fbae6bef63a77bd40222efe1fb1c78e8accf94f5271794be70d8b3b6 0x0208d4cc) (52 100)) ())
```

After change:
```
(venv) yakuhito@catstation:~/projects/clvm_tools$ brun -x 01 ff80ffff01ffff33ffa0099fb6be4707dde8e4ca595d34fbe8fa99cb30ca756d99c63a4d3dac1fd899f0ff8500540be40080ffff33ffa054801b54fbae6bef63a77bd40222efe1fb1c78e8accf94f5271794be70d8b3b6ff840208d4cc80ffff34ff648080ff8080
(() (q (51 0x099fb6be4707dde8e4ca595d34fbe8fa99cb30ca756d99c63a4d3dac1fd899f0 0x00540be400) (51 0x54801b54fbae6bef63a77bd40222efe1fb1c78e8accf94f5271794be70d8b3b6 0x0208d4cc) (52 100)) ())
```

The difference can be found in one of the CREATE_COIN conditions: the initial output is `0x02540be400` and the 'updated' one is `0x00540be400`. The correct one is `0x02540be400` (`10000000000`), so something is off when using `.toNumber()` with `SExp`. I will push a commit with the solution shortly - could you confirm that it solves the problem? Thanks.


yaku

**Comment by Yakuhito** [comment]
Ooops! It seems like I don't have permission to push commits on your branch. This is the change that I was talking about:

```
iff --git a/src/standard_coin.ts b/src/standard_coin.ts
index b6b99ae..f17dcdc 100644
--- a/src/standard_coin.ts
+++ b/src/standard_coin.ts
@@ -119,7 +119,7 @@ export class StandardCoin extends SmartCoin {
             Bytes.from(
                 Buffer.from(puzzleHash, "hex"),
             ),
-            amount.toNumber(),
+            Bytes.from(Util.coin.amountToBytes(amount), "hex"),
         ]);
     }
```

**Comment by polkom21** [comment]
Hello!

My changes work's fine in our app. You must check if signature is valid because we was a problems with your solution. Right now I can't find our thread in company with details but i remeber that we receiving negative values in CREATE_COIN instruction. Problem was not exists every time but afert verify signature we receiving always fail. Resolution was tested on mainnet. I will check your proposition with code 
```
Bytes.from(Util.coin.amountToBytes(amount), "hex"),
```
and let you know (pushing changes on my branch).

**Comment by Yakuhito** [comment]
Awesome. I'll merge the pull request once checks are complete and release a new version of GreenWeb.js after 3 changes:
 * Since `hexlify()` and `dehexlify()` are very useful, I'll move them to the `Util` class - they will be accesisble as `greenweb.util.hexlify()` and `greenweb.util.dehexlify()`.
 * I'll update `SmartCoin` and `CAT` to use the new methods as well
 * Tests, which were included in one of your previous commits.
I'll handle these things right now. Thank you very much for your contribution!

**Comment by Yakuhito** [comment]
aaand 1.1.7 is out! If you experience any other issues in the future, you can also reach me on Twitter/by email.

Thank you!

**Pull request merged**
